# Generated by Django 4.2.5 on 2023-09-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegie',
            name='recipe_image',
            field=models.ImageField(default='', upload_to='recipe/images'),
        ),
    ]
